{% set name = "shinywidgets" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shinywidgets-{{ version }}.tar.gz
  sha256: a88e7fa9e6825e478cb02fe52866900eb263b317976a3000b142695f8eb05383

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - ipywidgets >=7.6.5
    - jupyter_core
    - shiny >=0.6.1.9005
    - python-dateutil >=2.8.2

test:
  imports:
    - shinywidgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/posit-dev/py-shinywidgets
  summary: Render ipywidgets in Shiny applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
