{% set name = "shinywidgets" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shinywidgets-{{ version }}.tar.gz
  sha256: 417846a7d89717dfba4446af832faf0164a29fc8b0e6ccba3f6a8ab05623ba3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.6.5
    - jupyter_core
    - shiny >=0.6.1.9005
    - python-dateutil >=2.8.2

test:
  imports:
    - shinywidgets
  # commands:
    # broken by py-shiny feedstock
    # - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/posit-dev/py-shinywidgets
  summary: Render ipywidgets in Shiny applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
